config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :passes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: "passes#index"
  resources :passes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pass.rb
class Pass < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of     :login, :email
  validates_presence_of     :password,                   :if => :password_required?
  validates_presence_of     :password_confirmation,      :if => :password_required?
  validates_length_of       :password, :within => 4..40, :if => :password_required?
  validates_confirmation_of :password,                   :if => :password_required?
  validates_length_of       :login,    :within => 3..40
  validates_length_of       :email,    :within => 3..100
  validates_uniqueness_of   :login, :email, :case_sensitive => false
  before_save :encrypt_password

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login, password)
    u = find_by_login(login) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    crypted_password == encrypt(password)
  end

  def remember_token?
    remember_token_expires_at && Time.now.utc < remember_token_expires_at
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    self.remember_token_expires_at = 2.weeks.from_now.utc
    self.remember_token            = encrypt("#{email}--#{remember_token_expires_at}")
    #save(false)
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(false)
  end

  protected
  # before filter
  def encrypt_password
    return if password.blank?
    self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{login}--") if new_record?
    self.crypted_password = encrypt(password)
  end

  def password_required?
    crypted_password.blank? || !password.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  before_action :set_pass, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  # GET /passes
  # GET /passes.json
  def index
    @passes = Pass.all
  end

  # GET /passes/1
  # GET /passes/1.json
  def show
  end

  # GET /passes/new
  def new
    @pass = Pass.new
  end

  # GET /passes/1/edit
  def edit
  end

  # POST /passes
  # POST /passes.json
  def create
    @pass = Pass.new(pass_params)

    respond_to do |format|
      if @pass.save
        format.html { redirect_to @pass, notice: 'Pass was successfully created.' }
        format.json { render :show, status: :created, location: @pass }
      else
        format.html { render :new }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passes/1
  # PATCH/PUT /passes/1.json
  def update
    respond_to do |format|
      if @pass.update(pass_params)
        format.html { redirect_to @pass, notice: 'Pass was successfully updated.' }
        format.json { render :show, status: :ok, location: @pass }
      else
        format.html { render :edit }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passes/1
  # DELETE /passes/1.json
  def destroy
    @pass.destroy
    respond_to do |format|
      format.html { redirect_to passes_url, notice: 'Pass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pass
      @pass = Pass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pass_params
      params.require(:pass).permit(:name, :location, :login, :password, :additional)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Word5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "container">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="col-sm-8 col-md-3">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/passes/_form.html.erb
<%= form_with(model: pass, local: true) do |form| %>
  <% if pass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pass.errors.count, "error") %> prohibited this pass from being saved:</h2>

      <ul>
      <% pass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!--[form:pass]-->

  <p><label for="pass_name">Name:
    <%= text_field 'pass', 'name', :size =>  50 %></label></p>

  <p><label for="pass_location">Location:
    <%= text_field 'pass', 'location', :size =>  50 %></label></p>

  <p><label for="pass_login">Login:
    <%= text_field 'pass', 'login', :size =>  50 %></label></p>

  <p><label for="pass_password">Password:
    <%= text_field 'pass', 'password', :size =>  50 %></label></p>

  <p><label for="pass_location">Additional Information:</label>
    <%= text_area 'pass', 'additional', :rows => 3, :cols => 50 %></p>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/passes/edit.html.erb
<h1>Editing Pass</h1>

<%= render 'form', pass: @pass %>

<%= link_to 'Show', @pass %> |
<%= link_to 'Back to List', passes_path %>

app/views/passes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Login</th>
      <th>Password</th>
      <th>Additional</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @passes.each do |pass| %>
      <tr>
        <td><%= pass.name %></td>
        <td><%= pass.location %></td>
        <td><%= pass.login%></td>
        <td><%= pass.password%></td>
        <td><%= pass.additional%></td>
        <td><%= link_to 'Show', pass %></td>
        <td><%= link_to 'Edit', edit_pass_path(pass) %></td>
        <td><%= link_to 'Destroy', pass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pass', new_pass_path %>

app/views/passes/new.html.erb
<h1>New Pass</h1>

<%= render 'form', pass: @pass %>

<%= link_to 'Back', passes_path %>

app/views/passes/show.html.erb
<p id="notice"><%= notice %></p>



<p><label for="pass_location">Name:</label>
  <%= @pass.name %></p>

<p><label for="pass_location">Location:</label>
  <%= @pass.location %></p>

<p><label for="pass_login">Login:</label>
  <%= @pass.login %></p>

<p><label for="pass_password">Password:</label>
  <%= @pass.password %></p>

<p><label for="pass_location">Additional Information:</label>
  <%= @pass.additional %></p>




<%= link_to 'Edit', edit_pass_path(@pass) %> |
<%= link_to 'Back to List', passes_path %>